#ifndef NCURSES_COLORS_HPP
#define	NCURSES_COLORS_HPP

#define NC_COLOR_PAIR_VALUE_COLOR COLOR_BLUE
#define NC_COLOR_PAIR_VALUE 1
#define NC_COLOR_PAIR_VALUE_SET COLOR_PAIR(NC_COLOR_PAIR_VALUE) | A_BOLD

#define NC_COLOR_PAIR_NAME_COLOR COLOR_GREEN
#define NC_COLOR_PAIR_NAME 2
#define NC_COLOR_PAIR_NAME_SET COLOR_PAIR(NC_COLOR_PAIR_NAME) | A_BOLD

#define NC_COLOR_PAIR_ERROR_COLOR COLOR_RED
#define NC_COLOR_PAIR_ERROR 4
#define NC_COLOR_PAIR_ERROR_SET COLOR_PAIR(NC_COLOR_PAIR_ERROR)

#define NC_COLOR_PAIR_LESSER_COLOR COLOR_GRAY
#define NC_COLOR_PAIR_LESSER 5
#define NC_COLOR_PAIR_LESSER_SET COLOR_PAIR(NC_COLOR_PAIR_LESSER)

#endif
